export const PURCHASE_ORDER_REPORT = 'ADD_PURCHASE_ORDER_REPORT'
export const ADD_PURCHASE_ORDER_REPORT_SUCCESS = 'ADD_PURCHASE_ORDER_REPORT_SUCCESS'
export const ADD_PURCHASE_ORDER_REPORT_FAIL = 'ADD_PURCHASE_ORDER_REPORT_FAIL'
export const GET_PURCHASE_ORDER_REPORT = 'GET_PURCHASE_ORDER_REPORT'
export const GET_PURCHASE_ORDER_REPORT_SUCCESS = 'GET_PURCHASE_ORDER_REPORT_SUCCESS'
export const GET_PURCHASE_ORDER_REPORT_FAIL = 'GET_PURCHASE_ORDER_REPORT_FAIL'

