export const ADJUSTMENT = 'ADD_ADJUSTMENT'
export const ADD_ADJUSTMENT_SUCCESS = 'ADD_ADJUSTMENT_SUCCESS'
export const ADD_ADJUSTMENT_FAIL = 'ADD_ADJUSTMENT_FAIL'
export const GET_ADJUSTMENT = 'GET_ADJUSTMENT'
export const GET_ADJUSTMENT_SUCCESS = 'GET_ADJUSTMENT_SUCCESS'
export const GET_ADJUSTMENT_FAIL = 'GET_ADJUSTMENT_FAIL'

