export const PURCHASE_SUMMARY_REPORT = 'ADD_PURCHASE_SUMMARY_REPORT'
export const ADD_PURCHASE_SUMMARY_REPORT_SUCCESS = 'ADD_PURCHASE_SUMMARY_REPORT_SUCCESS'
export const ADD_PURCHASE_SUMMARY_REPORT_FAIL = 'ADD_PURCHASE_SUMMARY_REPORT_FAIL'
export const GET_PURCHASE_SUMMARY_REPORT = 'GET_PURCHASE_SUMMARY_REPORT'
export const GET_PURCHASE_SUMMARY_REPORT_SUCCESS = 'GET_PURCHASE_SUMMARY_REPORT_SUCCESS'
export const GET_PURCHASE_SUMMARY_REPORT_FAIL = 'GET_PURCHASE_SUMMARY_REPORT_FAIL'

