export const CASH_FLOW_SUMMARY = 'ADD_CASH_FLOW_SUMMARY'
export const ADD_CASH_FLOW_SUMMARY_SUCCESS = 'ADD_CASH_FLOW_SUMMARY_SUCCESS'
export const ADD_CASH_FLOW_SUMMARY_FAIL = 'ADD_CASH_FLOW_SUMMARY_FAIL'
export const GET_CASH_FLOW_SUMMARY = 'GET_CASH_FLOW_SUMMARY'
export const GET_CASH_FLOW_SUMMARY_SUCCESS = 'GET_CASH_FLOW_SUMMARY_SUCCESS'
export const GET_CASH_FLOW_SUMMARY_FAIL = 'GET_CASH_FLOW_SUMMARY_FAIL'

