export const EMPLOYEE_WISE_SALES = 'ADD_EMPLOYEE_WISE_SALES'
export const ADD_EMPLOYEE_WISE_SALES_SUCCESS = 'ADD_EMPLOYEE_WISE_SALES_SUCCESS'
export const ADD_EMPLOYEE_WISE_SALES_FAIL = 'ADD_EMPLOYEE_WISE_SALES_FAIL'
export const GET_EMPLOYEE_WISE_SALES = 'GET_EMPLOYEE_WISE_SALES'
export const GET_EMPLOYEE_WISE_SALES_SUCCESS = 'GET_EMPLOYEE_WISE_SALES_SUCCESS'
export const GET_EMPLOYEE_WISE_SALES_FAIL = 'GET_EMPLOYEE_WISE_SALES_FAIL'

